SGBot_Stage9 working bot
viramente/SpottyGlobeBot pull request #11
Opened 2024-02-10 00:40 UTC by viramente

2024-02-11 10:08 UTC, danelyan requested changes
В целом хорошо. Давай решим проблемку с энкодингом и чуть "приберемся"

2024-02-11 10:08 UTC, danelyan commented on src/main/kotlin/TelegramBotService.kt
> +fun sendMenu(botToken: String, chatId: Long): String {
Давай разместим все методы для работы с Telegram API внутри класса TelegramBotService.
Тогда внутри TelegramBotService можно сделать поле botToken, чтобы не передавать в каждый метод. А также вынести в константу "https://api.telegram.org/bot"

2024-02-11 10:08 UTC, danelyan commented on src/main/kotlin/TelegramBotService.kt
> +    val urlSendMessage = "https://api.telegram.org/bot$botToken/sendMessage?chat_id=$chatId&text=$message"
Чтобы "Старт" сработал, тут нужно сделать энкодинг строки message.

На самом деле урлы не поддерживают ряд символов.
Попробуй скопировать в строку адреса браузера `https://api.telegram.org/bot$botToken/sendMessage?chat_id=0&text=старт`, а потом копировать ее и вставить снова. Ты увидишь `%D1%81%D1%82%D0%B0%D1%80%D1%82` вместо русских символов.

Попробуй в коде сделать энкодинг:
`val encodedMessage = URLEncoder.encode(message, "UTF-8")`

2024-02-12 21:30 UTC, viramente commented
Я разобралась с энкодингом (и выписала себе в заметки шаблон); 
но не смогла при помощи энкодинга справиться с тем, что у меня юникод, -- надо ж как-то разбраться с двойным слэшем в итоге. Разве что еще вводить для этого случая форматирование строки. Но я не уверена, что это будет лучше мануального энкодинга. Или лучше?

2024-02-12 21:59 UTC, danelyan approved these changes

2024-02-20 16:14 UTC, merged