SGBot_Stage04 right word choosing
viramente/SpottyGlobeBot pull request #6
Opened 2024-01-03 23:45 UTC by viramente

2024-01-04 11:06 UTC, danelyan requested changes

2024-01-04 11:06 UTC, danelyan commented on src/main/kotlin/ConsoleTrainer.kt
> +    dictionarySource.writeText(
Это нам уже не нужно, по идее. 
Бот будет брать словарь из файла `words.txt`, туда же сохранять количества правильных ответов.
А так, ты постоянно перезаписываешь его своими значениями - прогресс не будет сохраняться.

Давай вынесем создание словаря в отдельный метод, например, `createInitialDictionary()`, в него положим твой код, но вызывать будем только если File.isExist == false при старте программы.

2024-01-04 11:06 UTC, danelyan commented on src/main/kotlin/ConsoleTrainer.kt
> +        door|дверь^3
да, разделитель может быть любым, благодаря работе split(). Если нравится, можно оставить `^`, разницы большой нету

2024-01-04 11:06 UTC, danelyan commented on src/main/kotlin/ConsoleTrainer.kt
> +                stringToParse[2].toInt() ?: 0
Тут elvis бесполезен, toInt никогда не будет Null, а будет просто падать.
Наверное ты хотела toIntOrNull() ?

2024-01-04 11:06 UTC, danelyan commented on src/main/kotlin/ConsoleTrainer.kt
>                  continue
Можно обойтись без continue в конце каждой ветки when, если добавить ветку else:
```Kotlin
when (input) {
            "1" -> { }
            "2" -> { }
            "0" -> break
            else ->  println("Вам следует выбрать пункт меню.")
        }
```

2024-01-04 11:06 UTC, danelyan commented on src/main/kotlin/ConsoleTrainer.kt
>  data class Word(val original: String, val translate: String, var correctAnswersCount: Int = 0)
Давай немного отформатируем. Разделение по строкам легче считывать глазами, чем запятую между параметрами в одной строке:
```Kotlin
data class Word(
    val original: String,
    val translate: String,
    var correctAnswersCount: Int = 0,
)

2024-01-04 11:06 UTC, danelyan commented on src/main/kotlin/ConsoleTrainer.kt
> +                    val wrongAnswers = (unlearnedWords - taskWord).toMutableList()
Хорошее решение!
И круто что учитывается нехватка невыученных слов - дополняется выученными.
Только мне не очень нравится, что много операций с коллекциями. Это ведь процессору, грубо говоря, надо в списке, найти элементы второго списка и удалить оттуда.

Давай немного алгоритм упростим / изменим:
1. Возьмем все невыученные слова (есть)
2. Возьмем оттуда POSED_ANSWERS_AMOUNT слов - это наш answers
3. Возьмем из полученных слов random() слово для изучения
4. Проверим, а хватает на до POSED_ANSWERS_AMOUNT, если нет - берем и находим невыученные слова (находим их только если нам правда не хватает, можно фильтром) и делаем shuffled.take(POSED_ANSWERS_AMOUNT - answers.size)

Дальше думаю понятно )

2024-01-04 11:06 UTC, danelyan commented on src/main/kotlin/ConsoleTrainer.kt
> +                } else {
этот else не нужен, так как ты делаешь break. Он только добавляет еще один уровень вложенности (которые желательно сокращать)

2024-01-04 14:50 UTC, viramente commented on src/main/kotlin/ConsoleTrainer.kt
> +                stringToParse[2].toInt() ?: 0
Не, я думала, а что если там будет не цифра вообще. Со строкой всё равно примерно, программа не рухнет, а тут рухнет. :)
Думала про поймать ошибку, но да, там не null, а NumberFormatException!
-- Внесла поправку.

2024-01-04 15:05 UTC, viramente commented on src/main/kotlin/ConsoleTrainer.kt
>                  continue
ммм... но я не хочу, чтобы тратились ресурсы на сравнивание с остальными ветками, поэтому я хочу сразу покинуть цикл when и пойти в меню. -- нет?

2024-01-05 08:01 UTC, danelyan commented on src/main/kotlin/ConsoleTrainer.kt
>                  continue
Оно и не будет тратиться, when отработает ветку и выйдет. Для эксперимента попробуй в точке проверки распечатать значение:

```Kotlin
when (input) {
            println("1").let { "1" } -> {
                val unlearnedWords = dictionary
                    .filter { it.correctAnswersCount < MATCHES_AMOUNT_TO_BECOME_LEARNED }

                if (unlearnedWords.isEmpty()) {
                    println("У вас нет невыученных слов!")
                    break
                }

                val answers = unlearnedWords.shuffled().take(POSED_ANSWERS_AMOUNT).toMutableList()

                val taskWord = answers.random()

                if (answers.size < POSED_ANSWERS_AMOUNT) {
                    val extraWrongAnswers = (dictionary - answers)
                        .shuffled()
                        .take(POSED_ANSWERS_AMOUNT - answers.size)
                    answers.addAll(extraWrongAnswers)
                }

                println("Выберете перевод для слова: ${taskWord.original}")

                answers.forEach { println("${answers.indexOf(it) + 1} ${it.translate}") }

                continue
            }

            println("2").let { "2" }-> {
                val learnedWordsAmount = dictionary.filter { it.correctAnswersCount >= 3 }.size

                println(
                    "Выучено $learnedWordsAmount из ${dictionary.size} слов " +
                            "| ${getPercents(dictionary.size, learnedWordsAmount)}%"
                )

                continue
            }

            println("0").let { "0" } -> break

        }
```

2024-01-05 08:01 UTC, danelyan commented on src/main/kotlin/ConsoleTrainer.kt
>                  continue
Вызовется для 1 только 1, для 0 - пройдут все ветки предшестующие 0

2024-01-05 13:04 UTC, danelyan commented on src/main/kotlin/ConsoleTrainer.kt
>                  continue
а, ну еще можно одинаковые условия добавить, убедиться что последующие такие же не отработают

2024-01-05 13:05 UTC, danelyan commented on src/main/kotlin/ConsoleTrainer.kt
> +                stringToParse[2].toInt() ?: 0
Так да, можно без try..catch, посмотри toIntOrNull():
```Kotlin
    dictionarySource.forEachLine {
        val stringToParse = it.split("|", "^")
        dictionary.add(
            Word(
                stringToParse[0],
                stringToParse[1],
                stringToParse[2].toIntOrNull() ?: 0
            )
        )
    }
```

2024-01-05 20:12 UTC, danelyan requested changes
Еще немного правок. И давай удалим stage02_task01.kt (и закоммитим удаление) - мы уже делаем бота в ConsoleTrainer, и это промежуточный файл нам не нужен

2024-01-05 20:12 UTC, danelyan commented on src/main/kotlin/ConsoleTrainer.kt
>          continue
Этот continue не нужен, у нас и так цикл закончился и дальше нет кода

2024-01-05 20:12 UTC, danelyan commented on src/main/kotlin/ConsoleTrainer.kt
>      val dictionarySource = File("words.txt")
Тут можно не создавать File дважды, сделать dictionarySource  и следом `if(!dictionarySource.exists()) ...`

2024-01-05 20:12 UTC, danelyan commented on src/main/kotlin/ConsoleTrainer.kt
> +
дело вкуса, но все же пустая строка - это своего рода средство выразительности (как абзацы в тексте), тут же каждое "предложение " в новом абзаце. Если тебе хочется больше пространства между строк, можно настроить в IDEA межстрочный интервал

2024-01-05 20:31 UTC, danelyan requested changes

2024-01-05 20:31 UTC, danelyan commented on src/main/kotlin/ConsoleTrainer.kt
> +    if (!File("words.txt").exists()) createInitialDictionary()
val dictionarySource = File("words.txt")
    if (!dictionarySource.exists()) createInitialDictionary()

2024-01-05 20:37 UTC, danelyan approved these changes
Отлично! Идем дальше )

2024-01-05 20:38 UTC, merged